version: '3.8'

services:
  coffee-tracker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
        - BACKEND_URL=https://coffee.rivs.com.br
    ports:
      - "80:80"
    restart: always
    labels:
      - "coolify.managed=true"
